force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <pluralLabel>Milestones</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>MasterDetail</type>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    </fields>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    </CustomObject>

force-app/main/default/objects/Milestone__c/fields/Percent_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Relationship to project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  Percent_Complete__c = 0,
  &quot;Not Started&quot;,
  IF(
    Percent_Complete__c = 100,
    &quot;Complete&quot;,
    &quot;In Progress&quot;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <pluralLabel>Projects</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Text</type>
        <length>50</length>
    </fields>
    </CustomObject>

force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-Do&apos;s</relationshipLabel>
    <relationshipName>To_Do_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started, In Progress, Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_MilestoneService.cls
/******************************
*  Class Name  :  Test_MilestoneService
* Version          : 1.0 
* Created Date     : Apr 10, 2025
* Function         : Test class for MilestoneService
* Modification Log :

* Developer                         Date                   Description
* ----------------------------------------------------------------------------                 
* Vinicius FIGUEIRA            10/Apr/2025            First Version
*****************************/

@isTest
public class Test_MilestoneService {
    @isTest
    static void testUpdateMilestoneProgress() {
        User u = [SELECT Id FROM User WHERE Profile.Name = 'Standard User' LIMIT 1];

        Project__c proj = new Project__c(Name = 'Test Project', OwnerId = u.Id);
        insert proj;

        Milestone__c ms = new Milestone__c(Name = 'Milestone 1', Project__c = proj.Id);
        insert ms;

        To_Do__c t1 = new To_Do__c(Name = 'Task 1', Milestone__c = ms.Id, Status__c = 'Complete');
        To_Do__c t2 = new To_Do__c(Name = 'Task 2', Milestone__c = ms.Id, Status__c = 'Not Started');
        insert new List<To_Do__c>{ t1, t2 };

        ms = [SELECT Id, Percent_Complete__c FROM Milestone__c WHERE Id = :ms.Id];
        System.assertEquals(50, ms.Percent_Complete__c);

        t2.Status__c = 'Complete';
        update t2;

        ms = [SELECT Percent_Complete__c FROM Milestone__c WHERE Id = :ms.Id];
        System.assertEquals(100, ms.Percent_Complete__c);

        delete t2;

        ms = [SELECT Percent_Complete__c FROM Milestone__c WHERE Id = :ms.Id];
        System.assertEquals(100, ms.Percent_Complete__c); // 1/1 still complete
    }
}