force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <pluralLabel>Milestones</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>MasterDetail</type>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    </fields>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    </CustomObject>

force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-Do&apos;s</relationshipLabel>
    <relationshipName>To_Do_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ToDoTriggerHandler.cls
/******************************
*  Class Name  :  ToDoTriggerHandler
* Version          : 1.0 
* Created Date     : Apr 10, 2025
* Function         : Handler class of ToDoTrigger
* Modification Log :

* Developer                         Date                   Description
* ----------------------------------------------------------------------------                 
* Vinicius FIGUEIRA            10/Apr/2025            First Version
*****************************/

public class ToDoTriggerHandler {
    public static void handleToDoChange(Set<Id> toDoIds) {
        // Query Milestone Ids from affected To-Dos
        Set<Id> milestoneIds = new Set<Id>();
        for (To_Do__c todo : [SELECT Id, Milestone__c FROM To_Do__c WHERE Id IN :toDoIds]) {
            if (todo.Milestone__c != null) {
                milestoneIds.add(todo.Milestone__c);
            }
        }

        if (!milestoneIds.isEmpty()) {
            MilestoneService.updateMilestoneProgress(milestoneIds);
        }
    }
}