force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <pluralLabel>Milestones</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>MasterDetail</type>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    </fields>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    </CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Relationship to project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <pluralLabel>Projects</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Text</type>
        <length>50</length>
    </fields>
    </CustomObject>

force-app/main/default/classes/MilestoneTriggerHandler.cls
/******************************
*  Class Name  :  MilestoneTriggerHandler
* Version          : 1.0 
* Created Date     : Apr 10, 2025
* Function         : Handler class of MilestoneTrigger
* Modification Log :

* Developer                         Date                   Description
* ----------------------------------------------------------------------------                 
* Vinicius FIGUEIRA            10/Apr/2025            First Version
*****************************/

public with sharing class MilestoneTriggerHandler {
    /**
     * Handles project progress update when Milestones are changed.
     * @param milestones - List of Milestones affected by insert/update/delete/undelete
     */
    public static void handleMilestoneChange(List<Milestone__c> milestones) {
        Set<Id> projectIds = new Set<Id>();

        // Extract all associated Project Ids from the changed milestones
        for (Milestone__c ms : milestones) {
            if (ms.Project__c != null) {
                projectIds.add(ms.Project__c);
            }
        }

        // Trigger project percent update only if we have related projects
        if (!projectIds.isEmpty()) {
            MilestoneService.updateProjectProgress(projectIds);
        }
    }
}