force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <pluralLabel>Milestones</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>MasterDetail</type>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    </fields>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    </CustomObject>

force-app/main/default/objects/Milestone__c/fields/Percent_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Relationship to project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  Percent_Complete__c = 0,
  &quot;Not Started&quot;,
  IF(
    Percent_Complete__c = 100,
    &quot;Complete&quot;,
    &quot;In Progress&quot;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <pluralLabel>Projects</pluralLabel>
    <nameField>
    <label>Name</label>
    <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
    <fullName>Percent_Complete__c</fullName>
    <label>Percent Complete</label>
    <type>Percent</type>
    <precision>2</precision>
    <scale>2</scale>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Text</type>
        <length>50</length>
    </fields>
    </CustomObject>

force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To-Do</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-Do&apos;s</relationshipLabel>
    <relationshipName>To_Do_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started, In Progress, Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_MilestoneTriggerHandler.cls
/******************************
*  Class Name  :  Test_MilestoneTriggerHandler
* Version          : 1.0 
* Created Date     : Apr 10, 2025
* Function         : Test class for MilestoneTriggerHandler
* Modification Log :

* Developer                         Date                   Description
* ----------------------------------------------------------------------------                 
* Vinicius FIGUEIRA            10/Apr/2025            First Version
*****************************/

@isTest
public class Test_MilestoneTriggerHandler {
    @isTest
    static void testProjectPercentCompleteUpdate() {
        //Create a Project with two Milestones
        Project__c project = new Project__c(Name = 'Project B');
        insert project;

        Milestone__c m1 = new Milestone__c(Name = 'M1', Project__c = project.Id);
        Milestone__c m2 = new Milestone__c(Name = 'M2', Project__c = project.Id);
        insert new List<Milestone__c>{ m1, m2 };

        //Assign To-Dos to both milestones
        To_Do__c t1 = new To_Do__c(Name = 'T1', Milestone__c = m1.Id, Status__c = 'Complete');
        To_Do__c t2 = new To_Do__c(Name = 'T2', Milestone__c = m1.Id, Status__c = 'Complete');
        To_Do__c t3 = new To_Do__c(Name = 'T3', Milestone__c = m2.Id, Status__c = 'Not Started');
        insert new List<To_Do__c>{ t1, t2, t3 };

        //  Get calculated average for the project
        m1 = [SELECT Percent_Complete__c FROM Milestone__c WHERE Id = :m1.Id];
        m2 = [SELECT Percent_Complete__c FROM Milestone__c WHERE Id = :m2.Id];
        project = [SELECT Percent_Complete__c FROM Project__c WHERE Id = :project.Id];

        //  Validate average = (100 + 0) / 2 = 50
        Decimal expectedAvg = ((Decimal)m1.Percent_Complete__c + m2.Percent_Complete__c) / 2;
        System.assertEquals(expectedAvg.setScale(2), project.Percent_Complete__c);

        // Complete the second milestone → expect project to be 100%
        t3.Status__c = 'Complete';
        update t3;

        project = [SELECT Percent_Complete__c FROM Project__c WHERE Id = :project.Id];
        System.assertEquals(100, project.Percent_Complete__c);
    }
}